<?php
/** @var array $Masks Массив масок*/
$Masks  = array (
    'UserNameAuth' => array(
                         'user_name' => array('func' => 'LatinName',
                                         'props' => array('min' => 3,'max'=> 15),
                                         'required' => true),
                         'password' => array('func' => 'LatinName',
                                        'props' => array('min' => 3,'max'=> 15),
                                        'required' => true),
    ),
    'PhoneAuth' => array(
                         'phone' => array('func' => 'StrNumbers',
                                               'props' => array('min' => 7,'max'=> 11),
                                               'required' => true),
                         'password' => array('func' => 'LatinName',
                                                  'props' => array('min' => 3,'max'=> 15),
                                                  'required' => true),
    ),
     'MailAuth' => array(
                         'e-mail' => array('func' => 'E_Mail',
                                                'props' => array(),
                                                'required' => true),
                         'password' => array('func' => 'LatinName',
                                        'props' => array('min' => 3,'max'=> 15),
                                        'required' => true),
     ),
    'StaffRegist' => array(
                           'user_name' => array('func' => 'LatinName',
                                           'props' => array('min' => 3,'max'=> 15),
                                           'required' => true),
                           'password' => array('func' => 'LatinName',
                                          'props' => array('min' => 3,'max'=> 15),
                                          'required' => true),
                           'first_name' => array('func' => 'LatinName',
                                            'props' => array('min' => 3,'max'=> 15),
                                            'required' => true),
                           'last_name' => array('func' => 'LatinName',
                                           'props' => array('min' => 3,'max'=> 15),
                                           'required' => true),
                           'middle_name' => array('func' => 'LatinName',
                                             'props' => array('min' => 3,'max'=> 15),
                                             'required' => true),
                           'date_of_birth' => array('func' => 'DateType',
                                               'props' => array('format' => 'd.m.Y', 'output' => 'int'),
                                               'required' => true),
                           'sys_role' => array('func' => 'ValueFromList',
                                           'props' => array('list' => array('admin','user','student')),
                                           'required' => true),
                           'phone' => array('func' => 'StrNumbers',
                                        'props' => array('min' => 7, 'max' => 11),
                                        'required' => true),
                           'e-mail' => array('func' => 'E_Mail',
                                        'props' => array(),
                                        'required' => true),
    ),
        'PersonRegist' => array(
                           'user_name' => array('func' => 'LatinName',
                                           'props' => array('min' => 3,'max'=> 15),
                                           'required' => true),
                           'password' => array('func' => 'LatinName',
                                           'props' => array('min' => 3,'max'=> 15),
                                           'required' => true),
                           'first_name' => array('func' => 'LatinName',
                                            'props' => array('min' => 3,'max'=> 15),
                                            'required' => true),
                           'last_name' => array('func' => 'LatinName',
                                           'props' => array('min' => 3,'max'=> 15),
                                           'required' => true),
                           'middle_name' => array('func' => 'LatinName',
                                             'props' => array('min' => 3,'max'=> 15),
                                             'required' => true),
                           'date_of_birth' => array('func' => 'DateType',
                                               'props' => array('format' => 'd.m.Y', 'output' => 'int'),
                                               'required' => true),
                           'phone' => array('func' => 'StrNumbers',
                                       'props' => array('min' => 7, 'max' => 11),
                                       'required' => true),
                           'e-mail' => array('func' => 'E_Mail',
                                        'props' => array(),
                                        'required' => true),
                           'document_type' => array('func' => 'RangedInt',
                                               'props' => array('min' => 1,'max'=> 6),
                                               'required' => true),
                           'document_number' => array('func' => 'AlphaNumeric',
                                                 'props' => array('min' => 6,'max'=> 10),
                                                 'required' => true),
                           'location_registrated' => array('func' => 'Text',
                                                      'props' => array('min' => 10,'max'=> 100),
                                                      'required' => true),
                           'real_location' => array('func' => 'Text',
                                               'props' => array('min' => 10,'max'=> 100),
                                               'required' => true),

        )
);

?>